### ISSUE TITLE
在用mosei训练时出现以下错误是为什么呢

### ISSUE THREAD

**Issue by Liucc2119** [kiva12138/CubeMLP#15]
Traceback (most recent call last):
  File "/data/kkzhang/cubemlp/Train.py", line 413, in <module>
    main()
  File "/data/kkzhang/cubemlp/Train.py", line 183, in main
    train_loader, valid_loader, test_loader = get_data_loader(opt)
  File "/data/kkzhang/cubemlp/DataLoaderUniversal.py", line 25, in get_data_loader
    dataset_train = CMUSDKDataset(mode='train', dataset='mosei', text=text, audio=audio, video=video, normalize=normalize, )
  File "/data/kkzhang/cubemlp/DataLoaderCMUSDK.py", line 110, in __init__
    self.l_features, self.a_features, self.v_features, self.labels, self.labels_2, self.labels_7 = get_mosei_dataset(mode=mode, text=text, audio=audio, video=video, normalize=normalize)
  File "/data/kkzhang/cubemlp/DataLoaderCMUSDK.py", line 80, in get_mosei_dataset
    assert video in mosei_v_features
AssertionError

**Comment by kiva12138** [comment]
你好，默认的训练参数是在MOSI上的，因此选择视频的参数也要根据数据集的变化而变化，而由于MOSEI数据集只提供facet42类型的视频特征，因此组要指定--video facet42，同时指定--d_v 35（如果没记错的话）。
